### ISSUE TITLE
创建实例显示状态错误

### ISSUE THREAD

**Issue by heyq001** [BillWang139967/openstack_install#8]
错误： 实例 "test" 执行所请求操作失败，实例处于错误状态。: 请稍后再试 [错误: 实例9c3fe7d0-b3ed-4f53-a74e-d379765514c4的构建已中止：Unable to establish connection to http://127.0.0.1:9696/v2.0/networks.json?id=a894b254-6a7e-4211-90d3-4ea6e1ce825e: HTTPConnectionPool(host='127.0.0.1', port=9696): Max retries exceeded with u].
照着步骤来安装的，在网页上创建实例一直提示这个错误。

**Comment by meetbill** [comment]
9696 端口是 Neutron 服务，检查下 neutron 服务是否正常工作

**Comment by heyq001** [comment]
已经解决了。在compute1上nova.conf配置文件里的neutron部分将URI的controller改成ip地址就行了。出错原因还是不知道。

**Comment by meetbill** [comment]
👍 
配置文件这块的配置
```
etc/main-config.rc:CONTROLLER_NODES="controller"
etc/main-config.rc:CONTROLLER_NODES_IP=“192.168.1.2”
```
程序在部署时会将 controller  和 IP 写入到 /etc/hosts 配置文件中，可以检查下 compute 机器上的 hosts 文件中的 IP 是否正确

**Comment by bigstar18** [comment]
请问里面是不是没有  创建这个节点的脚本 “Install and configure a storage node”？
只有controller and compute
能否加上？

**Comment by meetbill** [comment]
@bigstar18 小规模使用时，如果没有在虚拟机中挂载虚拟磁盘的需求，只需要controller and compute即可，企业中使用时 storage node 中块设备存储会使用 ceph 替代，文件存储一般公司会直接使用已有的存储，所以就没有加 storage node 的部分了

**Comment by sinydan** [comment]
同样出现 “Unable to establish connection to http://127.0.0.1:9696/v2.0/networks.json” 这种问题，确定了hosts文件没有问题，改了上述说的计算节点上的nova.conf，并没有解决问题

**Comment by nostalgicnick** [comment]
在compute节点，neutron里面配置了nova，需要 systemctl restart openstack-nova-compute.service

**Comment by codwd** [comment]
控制节点能当计算节点用吗

**Comment by codwd** [comment]
create volume时自动跳到登录页面,是没有ceph的吧

**Comment by meetbill** [comment]
Q:控制节点能当计算节点用吗
A:可以

Q:create volume时自动跳到登录页面,是没有ceph的吧
A:create volume 是创建块存储，需要有个 ceph 集群的

**Comment by codwd** [comment]
> Q:控制节点能当计算节点用吗
> A:可以
> 
> Q:create volume时自动跳到登录页面,是没有ceph的吧
> A:create volume 是创建块存储，需要有个 ceph 集群的

谢谢,另外,有没有kubernetes 对接 openstak的例子啊, k8s  install ccm.折腾了 好久

**Comment by meetbill** [comment]
我也没操作过
